### ISSUE TITLE
Merge call return HTTP error 502

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#33]
@mhiner 

here is stack trace
TypeError: Cannot read property 'split' of undefined
    at exports.getEditDistance (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/levenshtien.js:13:9)
    at calcScore (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/mergeDefinitions/definition.js:242:22)
    at Object.exports.definitions.Organization.calculateScore (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/mergeDefinitions/definition.js:115:11)
    at Object.exports.calculateScore (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/mergeDefinitions/definition.js:159:39)
    at scoreRecord (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:720:14)
    at findMatches (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:799:17)
    at /var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:603:25
    at /var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:352:5
    at callback (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:739:6)
    at Request._callback (/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/client.js:757:3)

/var/www/files_for_clients/dre/services/node_modules/dre-data/lib/levenshtien.js:13
          a = a.split(/[ \r\n\t]+/).join(' ').trim();

**Comment by igiware** [comment]
if it helps:
http://dre.ntrlab.ru:83/api/v1/merge/test - return 502 error
http://dre.ntrlab.ru:83/api/v1/merge/1 - return 200 with data
